export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import "@/app/globals.css";


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>{children}</div>
  )
}
